### PR TITLE
Support for execution of any single or multi query statements with discarded completions/rows

### PR DESCRIPTION
**Pull request by rolang**
Hi, I was looking for a way to execute any statements without being able to know in advance whether it's going to be a query or command as well as whether it'll contain single or multiple queries which is currently not possible.

Use case with some background:
We are using skunk in our code base for database access which has been working out great. For running migrations / versioning the database though we are still seeking support from [flyway](https://flywaydb.org). Considering that we only use a fraction of Flyway features, only with Postgres and we already have a library for database access which could take care of that, it adds a lot of dependencies on top like JDBC with drivers and keeps us tied to the JVM. Flyway cli also ships with a jre.

I am attempting to replace Flyway with [dumbo](https://github.com/rolang/dumbo). For that I'd like to read any SQL statements from a file, send it to Postgres and let it take care of the rest. Returned Completions/Rows are not really relevant. I'm currently missing the ability to let skunk just send any kind of statement, query or command, single or multiple to Postgres without the need to parse the contents or split into single statements.

I currently ended up with adding an extended Session version as in this PR that ships with a "simple"
```scala
def execute_(statement: Statement[Void]): F[Unit]
```
and was wondering whether this or something similar could be considered as part of skunk :thinking: 

Related issue about multi-query statements support: https://github.com/typelevel/skunk/issues/695
This one is maybe also somewhat related https://github.com/typelevel/skunk/issues/959

### CODE REVIEW

**Comment by mpilquist** [comment]
This seems like a good idea. Any ideas for a better name than `execute_`?

**Comment by rolang** [comment]
> This seems like a good idea. Any ideas for a better name than `execute_`?

How about `executeDiscard` (or `executeDiscarded`)?
I picked the idea with the `_` from cats where you have methods like `traverse` or `sequence` etc. going in pair with `traverse_` / `sequence_` as versions with discarded output, I thought it may fit as it builds on top of cats.
E.g. similar functionality in ZIO is named like `foreach` / `foreachDiscard`, `foreachPar` / `foreachParDiscard` etc.

**Comment by rolang** [comment]
I guess I could also add a version which accepts arguments if this extension is ok like:
`def executeDiscard[A](statement: Statement[Void])(args: A): F[Unit]` and also try to improve the code coverage.
I was not sure yet what to do with `NoticeResponse` messages, this one is not covered in the test.

**Comment by rolang** [comment]
Update:
- Renamed `execute_` to `executeDiscard`. Another name I just thought of is `executeVoid`, how about that :thinking:  ? 
- Discarding `NoticeResponse` as well instead of failing (not sure it needs to fail on that)
- updated sample queries in tests (something similar I've seen in the "wild" being done in migration scripts)

--- 

> I guess I could also add a version which accepts arguments  

I think I underestimated that one. It would make this pull request somewhat bigger :thinking:  I guess it would need to run through prepare as well and require a new type like `PreparedStatement` along with  `PreparedQuery` / `PreparedCommand`? Maybe it can be done as part of another update.

**Pull request merged**
